---
name: Deploy to render.
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to render.
        uses: gonuit/render-docker-deploy@v1.3.3
        with:
          render_email: ${{ secrets.RENDER_EMAIL }}
          ml_model_render_api_key: ${{ secrets.ML_MODEL_RENDER_API_KEY }}
          render_app_name: ${{ secrets.RENDER_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: --no-cache
          process_type: web
